security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt 
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username  # Changé de 'email' à 'username'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            entry_point: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
                # target: app_home

            # Enable CSRF protection
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: _username  # Changé de 'email' à '_username'
                password_parameter: _password  # Changé pour correspondre au formulaire

    access_control:
        # Define access control rules here
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }