vich_uploader:
    db_driver: orm
    mappings:
        user_avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        fleur_images:
            uri_prefix: /uploads/fleurs
            upload_destination: '%kernel.project_dir%/public/uploads/fleurs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer