controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\SecurityController::register